# -*- coding: utf-8 -*-
"""suc_transformersjs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OciKjgB-pakYBdjpWeu-duEcnhS49nsi
"""







!git clone https://github.com/huggingface/transformers.js-examples.git

!npm install @huggingface/inference

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/transformers.js-examples/llama-3.2-node
!node index.js

!node index.js

