# -*- coding: utf-8 -*-
"""suc_onnx_cpu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AtMp_KRleNa9f37-4Wtf8RVhCxdp2Mx4
"""







!pip install onnxruntime

!huggingface-cli login



"""شغال"""

!git clone https://huggingface.co/onnx-community/gemma-3-1b-it-ONNX

"""شغال"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/gemma-3-1b-it-ONNX/onnx
!wget https://huggingface.co/onnx-community/gemma-3-1b-it-ONNX/resolve/main/onnx/model.onnx

شغال

"""شغال"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/gemma-3-1b-it-ONNX/onnx
!wget https://huggingface.co/onnx-community/gemma-3-1b-it-ONNX/resolve/main/onnx/model_q4.onnx

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/gemma-3-1b-it-ONNX/onnx
!wget https://huggingface.co/onnx-community/gemma-3-1b-it-ONNX/resolve/main/onnx/model.onnx_data

"""### شغال"""

from transformers import AutoConfig, AutoTokenizer
import onnxruntime
import numpy as np

# 1. Load config, processor, and model
path_to_model = "/content/gemma-3-1b-it-ONNX"
config = AutoConfig.from_pretrained(path_to_model)
tokenizer = AutoTokenizer.from_pretrained(path_to_model)
decoder_session = onnxruntime.InferenceSession(f"{path_to_model}/onnx/model.onnx")

## Set config values
num_key_value_heads = config.num_key_value_heads
head_dim = config.head_dim
num_hidden_layers = config.num_hidden_layers
eos_token_id = 106 # 106 is for <end_of_turn>

# 2. Prepare inputs
## Create input messages
messages = [
  { "role": "system", "content": "You are a helpful assistant." },
  { "role": "user", "content": "Write me a poem about Machine Learning." },
]

## Apply tokenizer
inputs = tokenizer.apply_chat_template(messages, add_generation_prompt=True, tokenize=True, return_dict=True, return_tensors="np")

## Prepare decoder inputs
batch_size = inputs['input_ids'].shape[0]
past_key_values = {
    f'past_key_values.{layer}.{kv}': np.zeros([batch_size, num_key_value_heads, 0, head_dim], dtype=np.float32)
    for layer in range(num_hidden_layers)
    for kv in ('key', 'value')
}
input_ids = inputs['input_ids']
position_ids = np.tile(np.arange(1, input_ids.shape[-1] + 1), (batch_size, 1))

# 3. Generation loop
max_new_tokens = 1024
generated_tokens = np.array([[]], dtype=np.int64)
for i in range(max_new_tokens):
  logits, *present_key_values = decoder_session.run(None, dict(
      input_ids=input_ids,
      position_ids=position_ids,
      **past_key_values,
  ))

  ## Update values for next generation loop
  input_ids = logits[:, -1].argmax(-1, keepdims=True)
  position_ids = position_ids[:, -1:] + 1
  for j, key in enumerate(past_key_values):
    past_key_values[key] = present_key_values[j]

  generated_tokens = np.concatenate([generated_tokens, input_ids], axis=-1)
  if (input_ids == eos_token_id).all():
    break

  ## (Optional) Streaming
  print(tokenizer.decode(input_ids[0]), end='', flush=True)
print()

# 4. Output result
print(tokenizer.batch_decode(generated_tokens))

/content/gemma-3-1b-it-ONNX/onnx/model.onnx
/content/gemma-3-1b-it-ONNX/onnx/model.onnx_data
/content/gemma-3-1b-it-ONNX/onnx/model_q4.onnx

from transformers import AutoConfig, AutoTokenizer
import onnxruntime
import numpy as np

# 1. Load config, processor, and model
path_to_model = "/content/gemma-3-1b-it-ONNX"
config = AutoConfig.from_pretrained(path_to_model)
tokenizer = AutoTokenizer.from_pretrained(path_to_model)
decoder_session = onnxruntime.InferenceSession(f"{path_to_model}/onnx/model.onnx")

## Set config values
num_key_value_heads = config.num_key_value_heads
head_dim = config.head_dim
num_hidden_layers = config.num_hidden_layers
eos_token_id = 106 # 106 is for <end_of_turn>

# 2. Prepare inputs
## Create input messages
messages = [
  { "role": "system", "content": "You are a helpful assistant." },
  { "role": "user", "content": "Who is Rommel, the Desert Fox?" },
]

## Apply tokenizer
inputs = tokenizer.apply_chat_template(messages, add_generation_prompt=True, tokenize=True, return_dict=True, return_tensors="np")

## Prepare decoder inputs
batch_size = inputs['input_ids'].shape[0]
past_key_values = {
    f'past_key_values.{layer}.{kv}': np.zeros([batch_size, num_key_value_heads, 0, head_dim], dtype=np.float32)
    for layer in range(num_hidden_layers)
    for kv in ('key', 'value')
}
input_ids = inputs['input_ids']
position_ids = np.tile(np.arange(1, input_ids.shape[-1] + 1), (batch_size, 1))

# 3. Generation loop
max_new_tokens = 1024
generated_tokens = np.array([[]], dtype=np.int64)
for i in range(max_new_tokens):
  logits, *present_key_values = decoder_session.run(None, dict(
      input_ids=input_ids,
      position_ids=position_ids,
      **past_key_values,
  ))

  ## Update values for next generation loop
  input_ids = logits[:, -1].argmax(-1, keepdims=True)
  position_ids = position_ids[:, -1:] + 1
  for j, key in enumerate(past_key_values):
    past_key_values[key] = present_key_values[j]

  generated_tokens = np.concatenate([generated_tokens, input_ids], axis=-1)
  if (input_ids == eos_token_id).all():
    break

  ## (Optional) Streaming
  print(tokenizer.decode(input_ids[0]), end='', flush=True)
print()

# 4. Output result
print(tokenizer.batch_decode(generated_tokens))

"""شرح تفصيلي للكود وكيفية عمل البث المباشر:
تحميل المكونات الأساسية (السطور 1-12):
AutoConfig, AutoTokenizer: يتم تحميل إعدادات النموذج (مثل حجمه وعدد طبقاته) والأداة المسؤولة عن تحويل النص إلى أرقام (tokens) والعكس (tokenizer).
onnxruntime.InferenceSession: يتم تحميل ملف النموذج الفعلي بصيغة ONNX (model.onnx). هذه الصيغة محسّنة لسرعة الاستدلال (تشغيل النموذج).
num_key_value_heads, head_dim, num_hidden_layers: استخلاص بعض الإعدادات الهامة من ملف الإعدادات لاستخدامها لاحقاً.
eos_token_id: تحديد الرقم الخاص بالرمز الذي يدل على نهاية الجواب (<end_of_turn>).
تجهيز المدخلات للنموذج (السطور 14-27):
messages: تعريف المحادثة الأولية (رسالة النظام وسؤال المستخدم).
tokenizer.apply_chat_template: يقوم الـ tokenizer بتنسيق المحادثة بالشكل الذي يفهمه النموذج، ثم يحول النص إلى أرقام (input_ids).
past_key_values: إنشاء مصفوفات فارغة لتمثيل "ذاكرة النموذج" (KV Cache). هذه الذاكرة تساعد النموذج على تذكر ما قاله سابقاً لتسريع عملية التوليد. في البداية تكون فارغة.
input_ids: الأرقام التي تمثل سؤال المستخدم المنسق.
position_ids: أرقام تمثل موقع كل كلمة (token) في التسلسل (1, 2, 3...).
حلقة التوليد (Generation Loop) - (السطور 29-45): هذا هو الجزء الأهم للإجابة على سؤالك:
max_new_tokens: تحديد أقصى عدد للكلمات/الرموز الجديدة التي يمكن للنموذج توليدها.
generated_tokens: مصفوفة فارغة لتخزين الكلمات/الرموز التي سيتم توليدها.
for i in range(max_new_tokens):: تبدأ حلقة لتوليد الإجابة كلمة بكلمة (أو رمز برمز).
logits, *present_key_values = decoder_session.run(...): هنا يتم تشغيل النموذج. يُعطى النموذج الكلمة/الرمز الأخير (input_ids)، موقعها (position_ids)، وذاكرته (past_key_values). يُخرج النموذج:
logits: احتمالات لكل كلمة ممكنة في القاموس لتكون هي الكلمة التالية.
present_key_values: "ذاكرة النموذج" المحدثة بعد معالجة الإدخال الحالي.
input_ids = logits[:, -1].argmax(-1, keepdims=True): يتم اختيار الكلمة/الرمز التالي الأكثر احتمالاً بناءً على أعلى قيمة في logits. هذا الـ input_ids الجديد يحتوي الآن على كلمة واحدة فقط (الكلمة المولدة حديثاً).
position_ids = position_ids[:, -1:] + 1: تحديث موقع الكلمة التالية.
past_key_values[key] = present_key_values[j]: تحديث ذاكرة النموذج بالمعلومات الجديدة التي أخرجها.
generated_tokens = np.concatenate(...): إضافة الكلمة/الرمز الجديد إلى قائمة الكلمات المولدة.
if (input_ids == eos_token_id).all(): break: إذا كانت الكلمة المولدة هي رمز نهاية الجواب، تتوقف الحلقة.
print(tokenizer.decode(input_ids[0]), end='', flush=True): هذا هو السطر المسؤول عن عرض الإجابة كلمة بكلمة:
tokenizer.decode(input_ids[0]): يقوم الـ tokenizer بتحويل الرقم (ID) الخاص بالكلمة الجديدة فقط التي تم توليدها للتو إلى نص مقروء.
print(..., end=''): تطبع هذا النص بدون إضافة سطر جديد في النهاية. هذا يجعل الكلمة التالية تُطبع مباشرة بجانب السابقة.
flush=True: يجبر النظام على عرض النص المطبوع فوراً على الشاشة، بدلاً من الانتظار لتجميع مجموعة من المخرجات.
النتيجة: مع كل دورة في الحلقة، يتم توليد كلمة واحدة، تحويلها لنص، وطباعتها فوراً بدون سطر جديد، مما يعطي تأثير العرض كلمة بكلمة (البث المباشر).
عرض النتيجة النهائية (السطر 48):
print(tokenizer.batch_decode(generated_tokens)): بعد انتهاء الحلقة، يقوم هذا السطر بتحويل كل الكلمات/الرموز التي تم توليدها وتخزينها في generated_tokens إلى نص كامل مرة واحدة ويطبعه. (لكن التأثير المباشر كلمة بكلمة حدث بالفعل داخل الحلقة).
لماذا لا يُعرض أي شيء آخر غير الإجابة؟
السبب بسيط: الكود لا يحتوي على أي أوامر طباعة (print) أخرى داخل أو خارج حلقة التوليد تعرض متغيرات وسيطة أو رسائل تصحيح أخطاء (debugging messages). أوامر الطباعة الموجودة هي:
print(tokenizer.decode(input_ids[0]), end='', flush=True): داخل الحلقة، تطبع الكلمة المولدة للتو (وهذا جزء من الإجابة).
print(): بعد الحلقة، لطباعة سطر جديد فقط لفصل الإجابة عن أي شيء قد يأتي بعدها في الطرفية.
print(tokenizer.batch_decode(generated_tokens)): بعد الحلقة، لطباعة الإجابة الكاملة (وهي اختيارية إذا كان العرض المباشر كافياً).
بما أنه لا توجد أوامر print أخرى، فلن ترى أي مخرجات إضافية غير الإجابة التي يتم توليدها وعرضها تدريجياً.
"""